build:
  script:
    - git submodule init
    - git submodule update
    - ./compile.sh -DTEST=true
    - ./build/multithreaded_observer_test
  after_script:
    - cd /media/storage/gitlab/
    - rm -rf Multithreaded_Observer
    - git clone http://git.home.lan/root/Multithreaded_Observer.git
    - cd Multithreaded_Observer
    - git submodule init
    - git submodule update
